stages:
  - build-backend
  - test
  - jacoco
  - spotbugs
  - build-frontend
  - lint
  - vitest

cache:
  paths:
    - .m2/repository
    - Project/Frontend/node_modules

backend-build:
  stage: build-backend
  script:
    - rm -f .m2/repository/net/bytebuddy/byte-buddy/1.14.19/byte-buddy-1.14.19.jar
    - cd Project/Backend
    - mvn dependency:purge-local-repository -DreResolve=false -DactTransitively=false -DmanualInclude=net.bytebuddy:byte-buddy
    - mvn compile

backend-test:
  stage: test
  script:
    - cd Project/Backend
    - mvn test

backend-jacoco:
  stage: jacoco
  script:
    - cd Project/Backend
    - mvn verify

backend-spotbugs:
  stage: spotbugs
  script:
    - cd Project/Backend
    - mvn spotbugs:check

frontend-build:
  stage: build-frontend
  script: 
    - cd Project/Frontend
    - npm ci
    - npm run build

frontend-lint:
  stage: lint
  script: 
    - cd Project/Frontend
    - npm run lint 