stages:
  - build
  - test
  - jacoco
  - checkstyle
  - spotbugs

cache:
  paths:
    - .m2/repository

build:
  stage: build
  script:
    - cd Project/Backend
    - mvn compile

test:
  stage: test
  script:
    - cd Project/Backend
    - mvn test

jacoco:
  stage: jacoco
  script:
    - cd Project/Backend
    - mvn verify

eslint:
  stage: checkstyle
  script:
    - cd Project/Frontend
    - npm install
    - npx eslint . --ext .js,.jsx,.ts,.tsx

spotbugs:
  stage: spotbugs
  script:
    - cd Project/Backend
    - mvn spotbugs:check
