stages:
  - build
  - test
  - jacoco
  - spotbugs

cache:
  paths:
    - .m2/repository

build:
  stage: build
  script:
    - cd Project/Backend
    - mvn compile

test:
  stage: test
  script:
    - cd Project/Backend
    - mvn test

jacoco:
  stage: jacoco
  script:
    - cd Project/Backend
    - mvn verify

spotbugs:
  stage: spotbugs
  script:
    - cd Project/Backend
    - mvn spotbugs:check
