on: push

jobs:
  backend-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Remove ByteBuddy jar
        run: rm -f ~/.m2/repository/net/bytebuddy/byte-buddy/1.14.19/byte-buddy-1.14.19.jar
      - name: Purge ByteBuddy dependency
        run: mvn dependency:purge-local-repository -DreResolve=false -DactTransitively=false -DmanualInclude=net.bytebuddy:byte-buddy
        working-directory: Project/Backend
      - name: Compile backend
        run: mvn compile
        working-directory: Project/Backend

  backend-test:
    runs-on: ubuntu-latest
    needs: backend-build
    steps:
      - uses: actions/checkout@v3
      - name: Run backend tests
        run: mvn test
        working-directory: Project/Backend

  backend-jacoco:
    runs-on: ubuntu-latest
    needs: backend-test
    steps:
      - uses: actions/checkout@v3
      - name: Run Jacoco
        run: mvn verify
        working-directory: Project/Backend

  backend-spotbugs:
    runs-on: ubuntu-latest
    needs: backend-test
    steps:
      - uses: actions/checkout@v3
      - name: Run SpotBugs
        run: mvn spotbugs:check
        working-directory: Project/Backend

  frontend-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
        working-directory: Project/Frontend
      - name: Build frontend
        run: npm run build
        working-directory: Project/Frontend

  frontend-lint:
    runs-on: ubuntu-latest
    needs: frontend-build
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Run linter
        run: npm run lint
        working-directory: Project/Frontend
